version: "3.9"

services:

  api:
    build: .
    env_file:
      - .env
    volumes:
      - .:/flights
    ports:
      - "8000:8000"
    command: uvicorn flights.main:api --host 0.0.0.0 --port 8000 --reload --log-level debug
